const GENRES = [
    { name: "Action", value: "Action"},
    {name:"Architecture", value: "Architecture"},
    {name: "Alternate history", value: "Alternate_history"},
    {name: "Autobiography", value: "Autobiography"},
    {name: "Anthology", value: "Anthology"},
    {name: "Biography", value: "Biography"},
    {name: "Chick lit", value: "Chick_lit"},
    {name: "Business", value: "Business"},
    {name: "Children's", value: "Children's"},
    {name: "Crafts", value: "Crafts"},
    {name: "Classic", value: "Classic"},
    {name: "Cookbook", value: "Cookbook"},
    {name: "Diary", value: "Diary"},
    {name: "Coming-of-age", value: "Coming-of-age"},
    {name: "Dictionary", value: "Dictionary"},
    {name: "Crime", value: "Crime"},
    {name: "Encyclopedia", value: "Encyclopedia"},
    {name: "Drama", value: "Drama"},
    {name: "Fairytale", value: "Fairytale"},
    {name: "Fiction", value: "fiction"},
    {name: "Health", value: "Health"},
    {name: "Fantasy", value: "Fantasy"},
    {name: "History", value: "History"},
    {name: "Graphic novel", value: "Graphic_novel"},
    {name: "Historical fiction", value: "Historical_fiction"},
    {name: "Humor", value: "Humor"},
    {name: "Horror", value: "Horror"},
    {name: "Journal", value: "Journal"},
    {name: "Mystery", value: "Mystery"},
    {name: "Math", value: "Math"},
    {name: "Non-fiction", value: "Non_fiction"},
    {name: "Paranormal romance", value: "Paranormal_romance"},
    {name: "Memoir", value: "Memoir"},
    {name: "Picture book", value: "Picture_book"},
    {name: "Philosophy", value: "Philosophy"},
    {name: "Poetry", value: "Poetry"},
    {name: "Prayer", value: "Prayer"},
    {name: "Political thriller", value: "Political_thriller"},
    {name: "Religion", value: "Religion"},
    {name: "Romance", value: "Romance"},
    {name: "Textbook", value: "Textbook"},
    {name: "Satire", value: "Satire"},
    {name: "True crime", value: "True_crime"},
    {name: "Science fiction", value: "Science_fiction"},
    {name: "Review", value: "Review"},
    {name: "Short story", value: "Short_story"},
    {name: "Science", value: "Science"},
    {name: "Suspense", value: "Suspense"},
    {name: "Self help", value: "Self_help"},
    {name: "Thriller", value: "Thriller"},
    {name: "Sports", value: "Sports"},
    {name: "Western", value: "Western"},
    {name: "Travel", value: "Travel"},
    {name: "Young adult", value: "Young_adult"}
]

export default GENRES